In [1]:
import pandas as pd
import os
import datetime as dt

In [2]:
csv_file = '/Descargas/datathon/datos/CM02_2/pernoctaciones_viajeros_entradas.csv'

In [3]:
df = pd.read_csv(csv_file)

In [4]:
o_tot = df[(df['origen'] == 'TOTAL')].index
df.drop(o_tot, inplace = True)

In [5]:
v_alo = df[(df['indicador'] == "Viajeros alojados")].index
df.drop(v_alo , inplace=True)

In [6]:
anios = ["2009","2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021"]
for x in anios:
    sn = df[(df['periodo'] == x)].index
    df.drop(sn , inplace=True)

In [7]:
df["Año"] = df["periodo"].str[:4]
df["Mes"] = df["periodo"].str[-2:]

In [8]:
zip_file = '/Descargas/datathon/Catalogo de zipcodes.csv'
zp = pd.read_csv(zip_file)

In [9]:
zp

,C¢digo INE,Municipio,Poblaci¢n (2018),Superficie (km),Provincia,Isla
0,38001,Adeje,47280,10595,Santa Cruz de Tenerife,Tenerife
1,38002,Agulo,1067,2539,Santa Cruz de Tenerife,La Gomera
2,38003,Alajer¢,2006,4942,Santa Cruz de Tenerife,La Gomera
3,38004,Arafo,5562,3427,Santa Cruz de Tenerife,Tenerife
4,38005,Arico,7931,17876,Santa Cruz de Tenerife,Tenerife
...,...,...,...,...,...,...
83,35030,Tuineje,15241,27593,Las Palmas,Fuerteventura
84,35032,Valleseco,3749,2211,Las Palmas,Gran Canaria
85,35031,Valsequillo,9340,3915,Las Palmas,#N/D
86,35033,San Mateo,7556,3789,Las Palmas,#N/D
87,35034,Yaiza,16571,21184,Las Palmas,Lanzarote

In [10]:
df2 = df.merge(zp, left_on = "municipio", right_on = "Municipio")

In [11]:
df2

,indicador,origen,municipio,periodo,valor,Año,Mes,C¢digo INE,Municipio,Poblaci¢n (2018),Superficie (km),Provincia,Isla
0,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2021M07,2431,2021,07,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
1,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2021M06,2446,2021,06,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
2,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2021M05,2462,2021,05,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
3,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2021M04,1692,2021,04,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
4,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2021M03,1191,2021,03,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59791,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2009M05,0,2009,05,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro
59792,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2009M04,0,2009,04,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro
59793,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2009M03,2,2009,03,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro
59794,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2009M02,0,2009,02,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro
59795,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2009M01,16,2009,01,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro

In [12]:
df2[pd.to_numeric(df2["valor"], errors='coerce')

,indicador,origen,municipio,periodo,valor,Año,Mes,C¢digo INE,Municipio,Poblaci¢n (2018),Superficie (km),Provincia,Isla
12,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2020M07,..,2020,07,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
13,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2020M06,..,2020,06,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
14,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2020M05,..,2020,05,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
15,Pernoctaciones,TOTAL RESIDENTES EN EL EXTRANJERO,Arrecife,2020M04,..,2020,04,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
163,Pernoctaciones,Alemania,Arrecife,2020M07,..,2020,07,35004,Arrecife,62988,2272,Las Palmas,Lanzarote
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59509,Viajeros entrados,Canarias,El Pinar de El Hierro,2020M04,..,2020,04,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro
59657,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2020M07,..,2020,07,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro
59658,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2020M06,..,2020,06,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro
59659,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2020M05,..,2020,05,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro
59660,Viajeros entrados,Residentes en España excepto Canarias,El Pinar de El Hierro,2020M04,..,2020,04,38901,El Pinar de El Hierro,1825,8495,Santa Cruz de Tenerife,El Hierro

In [35]:
df2 = df2[df2.valor != ".."]

In [40]:
df2["valor"] = df2["valor"].astype(int)

D:\Documentos\Temp/ipykernel_3212/1986689443.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["valor"] = df2["valor"].astype(int)

In [43]:
pv = pd.pivot_table(df2, values="valor", index = 'C¢digo INE', columns = 'indicador')

In [46]:
pv["NochesPorPersona"] = round(pv["Pernoctaciones"]/pv["Viajeros entrados"])

In [47]:
pv

indicador   Pernoctaciones  Viajeros entrados  NochesPorPersona
C¢digo INE
35003         36909.064935        4804.465059               8.0
35004          2865.319728         784.554113               4.0
35014         50122.868275        6072.670377               8.0
35017           414.144201         213.594984               2.0
35024         64443.198516        8034.096475               8.0
35034         81962.232529       10091.612863               8.0
38001        189236.312925       23876.075448               8.0
38006        139673.783550       17293.184910               8.0
38017          3647.648732         706.478664               5.0
38024          4542.846011         664.965986               7.0
38027           919.222016         114.810142               8.0
38028         74844.714904       10198.987013               7.0
38037           975.510204         319.474335               3.0
38038          6763.150278        3033.604205               2.0
38040         26037.598021        3341.605442               8.0
38048           416.608534         128.425479               3.0
38049          5814.039579         710.444032               8.0
38901           154.228819          33.631416               5.0

In [55]:
pv.to_csv('/Descargas/datathon/Finished_pernoctas.csv')